network:
  ethernets:
    ib0:
      addresses:
        - 25.8.0.20/24
      dhcp4: 'false'
      renderer: networkd
    ib1:
      dhcp4: false
      addresses:
        - 12.0.0.20/24
      renderer: networkd
  version: 2
